server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/userServiceFallBack
                statusCodes:
                  - SERVICE_UNAVAILABLE
                  - BAD_GATEWAY
                  - GATEWAY_TIMEOUT
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
          filters:
            - name: CircuitBreaker
              args:
                name: contact-service
                fallbackUri: forward:/contactServiceFallBack
                statusCodes:
                  - SERVICE_UNAVAILABLE
                  - BAD_GATEWAY
                  - GATEWAY_TIMEOUT


hystrix:
  command:
    fallbackCmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream,health,info"
  endpoint:
    health:
      show-details: "always"
