apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-service-app
  labels:
    app: contact-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-service-app
  template:
    metadata:
      labels:
        app: contact-service-app
    spec:
      containers:
        - name: contact-service-app
          image: rchauhan9102/contact-service
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "750m"
          ports:
            - containerPort: 9001
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:-UseContainerSupport"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://cloud-config-server-svc:80"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"

---
apiVersion: v1
kind: Service
metadata:
  name: contact-service-svc
spec:
  ports:
    - targetPort: 9002
      port: 80
  selector:
    app: contact-service-app