server:
  port: 8760
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server: 
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
  serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/