server:
  port: 8760
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server: 
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: "${HOSTNAME}.eureka"
  serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}