server:
  port: 9296

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rahul-Chauhan-2212/config-server.git
          cloneOnStart: true
          defaultLabel: main
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8760/eureka
---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Rahul-Chauhan-2212/config-server.git"
          cloneOnStart: true
          defaultLabel: main
          searchPaths: "kubernetes"
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8760/eureka}

    
